baseurl         = "/"
theme = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "DataAnt"
  subtitle    = "Average Analyst"
  copyright   = "© 2020"

  cover       = "img/blog-cover.jpg"
  description = "Personal Data Blog"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "Vignesh_Appanraj"
  #fbName = "fakeghost"
  githubName = "madeye28"
  linkedinName = "Vignesh Appanraj"
  mediumName = ""

  logo = ""
  orgName = "DataAnt"
  orgWebsite = ""
  orgDescription = ""

  showSupport = true

  author = "Vignesh A"
  authorAvatar = "img/vikki.jpg"
  authorLocation = "India"
  authorWebsite = "https://github.com/madeye28"
  authorDescription = "Live, let Live"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200


[[menu.main]]
  name = "Post"
  url = "/post/"
  weight = 200



[[menu.main]]
  name = "Twitter"
  url = "https://twitter.com/AppanrajVignesh"
  weight = 95

[[menu.main]]
  name = "COVID-19 Dashboard"
  url = "/categories/COVID-19 Dashboard/"
  weight = 99


[[menu.main]]
  name = "Python"
  url = "/categories/Python/"
  weight = 99

[[menu.main]]
  name = "R"
  url = "/categories/r/"
  weight = 99
