baseurl         = "/"
theme = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "DataAnt"
  subtitle    = "Average Analyst"
  copyright   = "© 2020"

  cover       = "img/blog-cover.jpg"
  description = "Personal Data Blog"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "Vignesh_Appanraj"
  #fbName = "fakeghost"
  githubName = "madeye28"
  linkedinName = "Vignesh Appanraj"
  mediumName = ""

  logo = "da.ico"
  orgName = "DataAnt"
  orgWebsite = ""
  orgDescription = ""

  showSupport = true

  author = "Vignesh A"
  authorAvatar = "vikki.jpg"
  authorLocation = "India"
  authorWebsite = "https://github.com/madeye28"
  authorDescription = "Engineer by degree, Data Analyst by heart"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95


