baseurl         = "/"
theme = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "DataAnt"
  subtitle    = "Average Analyst"
  copyright   = "© 2020"

  cover       = "img/blog-cover.jpg"
  description = "Personal Data Blog"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "faketryghost"
  fbName = "fakeghost"
  githubName = "eueung"
  linkedinName = "eueung"
  mediumName = ""

  logo = ""
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "Vignesh A"
  authorAvatar = "img/vikki.jpg"
  authorLocation = "India"
  authorWebsite = "https://github.com/madeye28"
  authorDescription = "Engineer by degree, Data Analyst by heart"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Go"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95


